include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    ["**/*.g.dart", "**/*.freezed.dart", "**/*.gen.dart", "**/*.freezed.g.dart"]

linter:
  rules:
