name: flutter_base_project_riverpod
description: "A base project for Flutter."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # state
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # localization
  intl_utils: ^2.8.7
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # storage
  shared_preferences: ^2.2.0
  path_provider: ^2.1.1
  file_picker: ^8.1.4
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # network
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0

  # logger
  logger: ^2.5.0

  # widget
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.2
  cupertino_icons: ^1.0.8

  # utils
  envied: ^1.0.0
  freezed_annotation: ^2.4.1

  # lint
  custom_lint: ^0.7.0

  #dependency injection
  get_it: ^8.0.3

  # router
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.2
  hive_generator: ^2.0.1
  retrofit_generator: ^9.1.5
  json_serializable: ^6.8.0
  envied_generator: ^1.0.0
  flutter_gen_runner: ^5.8.0
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  arb_dir: lib/generated/l10n
  output_dir: lib/generated/l10n/l10n_gen
  main_locale: en

flutter_gen:
  output: lib/generated/assets
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/colors.xml
